# Generated by Django 4.1 on 2022-08-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('ClienteId', models.AutoField(primary_key=True, serialize=False)),
                ('ClienteNome', models.CharField(max_length=500)),
                ('ClienteEmail', models.EmailField(max_length=500)),
                ('ClienteTelefone', models.CharField(max_length=500)),
                ('ClienteEndereco', models.CharField(max_length=500)),
                ('ClienteProfissao', models.CharField(max_length=500)),
                ('ClinteCurriculo', models.CharField(max_length=500)),
            ],
        ),
    ]
